name: KnockoutPlus
main: io.github.archemedes.knockoutplus.KnockoutPlus
description: This plugin puts the 'cute' back in execute. Fight to the death or friendly brawl? The choice is yours. 
version: ${project.version}
depend: [ProtocolLib, Tythan, RPPersonas]
softdepend: [Omniscience, WorldGuard]
authors: [Arche, Kowaman]
api-version: 1.13

commands:
   revive:
      description: This command lets you assist a knocked out character.
      permission: knockoutplus.revive
      usage: /revive [player]
   reviveall:
      description: This command saves all currently knocked out players
      usage: /reviveall
   damage:
     description: This command causes you to damage yourself
     permission: knockoutplus.revive
     aliases: [d]
     usage: /damage [damage amount]
   d20:
     description: Instant ko-worthy damage
     permission: knockoutplus.revive
     usage: /d20
     aliases: [d40, d48]
   togglerevive:
      description: This command lets you assist a knocked out character.
      permission: archecore.mod
      usage: /togglerevive [mobs/environment/players/all]
   knockoutplus:
      description: List current KOs and status of flags.
      permission: knockoutplus.knockout
      aliases: [knockoutplus, kp, ko]
      usage: /<command> [list/status]
   wcstats:
     description: Stats for war team